### ISSUE TITLE
Constrain the possible markets

### ISSUE THREAD

**Issue by metaproph3t** [metaDAOproject/openbook-twap#2]
In the interest of security, it probably makes sense to constrain the possible TWAP-able markets to a simple case we can reason about and test

Here are some assertions we should run:
- `market.time_expiry` == 0 (markets don't expire)
- `open_orders_admin` and `close_market_admin` == our twap market
- `consume_events_admin` == `Pubkey::default()` (this is how `NonZeroPubkeyOption` records a `None`)
- `oracle_a` and `oracle_b` == `Pubkey::default()` (oracle-pegged orders might create some edge cases)
- `seq_num` == 0? maybe there are some edge cases where market is initialized and traded in before twap?
- `maker_fee` == 0? 
- `taker_fee` == 0? it feels like there are some weird edge cases with fees where someone uses a high taker fee to convey that the market is at a certain price, but it's actually not

**Comment by metaproph3t** [comment]
just realized `seq_num` should always be 0 since we're the open order admin

still probably wise to check

**Comment by soundsonacid** [comment]
I can do this later today if you do not have the bandwidth to get done today

**Comment by soundsonacid** [comment]
I see that this is already done in the CreateTWAPmarket ix actually

**Comment by metaproph3t** [comment]
I see that most checks are in there; would you be able to add the remaining?

**Comment by metaproph3t** [comment]
also, would this ever be triggered? https://github.com/metaDAOproject/openbook-twap/blob/962606c4c18f21c24002bbbbf7fad999da91c300/programs/openbook-twap/src/lib.rs#L389-L392

since it's a uint

**Comment by metaproph3t** [comment]
addressed by this: https://github.com/metaDAOproject/openbook-twap/pull/6
